default: main.cpp creature.h creature.cpp gollum.h gollum.cpp barbarian.h barbarian.cpp babayaga.h babayaga.cpp bluemen.h bluemen.cpp unicorn.h unicorn.cpp
	g++ main.cpp creature.cpp gollum.cpp barbarian.cpp babayaga.cpp bluemen.cpp unicorn.cpp -o monster

clean:
	rm -f *.o monster
