default: main.cpp game.cpp game.h floor.cpp floor.h actor.cpp actor.h swan.cpp swan.h player.cpp player.h
	g++ main.cpp game.cpp floor.cpp actor.cpp swan.cpp player.cpp -o maze

clean:
	rm -f *.o maze
